name: Teste Marco
favicon: null
layout_spectrum: 0.8
title: Teste Marco
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#738896'
    - '#09080e'
    - '#fdb69f'
    - '#e2fefe'
    - '#21324a'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: follow
    item: null
    url: null
